services:
  - type: web
    name: geopolitical-intelligence-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # You'll need to set this manually in Render dashboard
      - key: FRONTEND_URL
        value: https://geop-frontend-yes.vercel.app
    healthCheckPath: /health 